name: build docker images

on:  
  push:    
    branches: [ main ]

jobs:
  klipper:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_KEY }}
      -
        name: Build and push klipper
        uses: docker/build-push-action@v2
        with:
          context: ./klipper
          platforms: linux/arm/v7
          push: true
          tags: |
            saxmfone1/klipper:latest
          cache-from: type=registry,ref=saxmfone1/klipper:latest
          cache-to: type=inline

  moonraker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_KEY }}
      -
        name: Build and push moonraker
        uses: docker/build-push-action@v2
        with:
          context: ./moonraker
          platforms: linux/arm/v7
          push: true
          tags: |
            saxmfone1/moonraker:latest
          cache-from: type=registry,ref=saxmfone1/moonraker:latest
          cache-to: type=inline
  fluidd:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_KEY }}
      -
        name: Build and push fluidd
        uses: docker/build-push-action@v2
        with:
          context: ./fluidd
          platforms: linux/arm/v7
          push: true
          tags: |
            saxmfone1/fluidd:latest
          cache-from: type=registry,ref=saxmfone1/fluidd:latest
          cache-to: type=inline
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install plugins
        run: npm install @semantic-release/git @semantic-release/changelog -D
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
